version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    command: serve
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: 4g
    # Falls du eine NVIDIA GPU nutzt, entferne das Kommentarzeichen unten:
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility

volumes:
  ollama_data: