services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: /bin/sh -c "ollama serve & sleep 5 && ollama pull llama3.2 && wait"
    restart: unless-stopped

volumes:
  ollama_data: